trigger: none

pool:
  vmImage: 'ubuntu-16.04'

steps:
 - script: echo "Hello dinesh!!! It's single stage with single job pipeline"

 # first yml file
 # single stage, single job file doest require those keywords, directly add steps